### ISSUE TITLE
getCurrentWindow potentially loses children windows

### ISSUE THREAD

**Issue by AndyMJones** [symphonyoss/ContainerJS#134]
The current implementation of `getCurrentWindow` creates a new `ssf.window` wrapper around the `innerWindow`. This means that it is possible (and likely) to have two `ssf.windows` pointing to the same `innerWindow` however they will have different children and listeners to each other. 

The parent that creates a window and the child window itself both have their own wrapper around the `innerWindow`. So once the child creates another window or adds a listeners, the parent still has a wrapper that says there are no children or listeners.

I have investigated a few solutions however none of them seem ideal. One would be to put a reference of the child on the parent window and have the child use `window.opener` to get the currenty `ssf.window` rather than creating a new one, however this may not work at all for electron.

Another solution could be to have a higher up window or manager window that isnt shown and is a state of truth for all the other windows so that their references don't get out of sync. This solution could work however it would be a big task.

**Comment by BenLambertNcl** [comment]
I think for Electron, keeping track of a windows children would be doable using the main process as our single source of truth. We could keep a tree like object of all windows and their children, which we can just get via IPC when we call `getChildWindows`. Obviously this isn't possible for OpenFin though.

**Comment by nkolba** [comment]
John, Ben,

Could you explain the scenario in more detail?  Not really sure how the "innerWindow" is implemented and the reason for having it.

Typically, if we want to maintain state between multiple windows in an OpenFin app, we'll either use a persistent parent window (or hidden background window/render process), or web standard solutions like local storage or a shared worker.

-Nick

**Comment by BenLambertNcl** [comment]
@nkolba Our `innerWindow` is the container specific window object. This could be the current window or a window that has been opened using `fin.desktop.Window` for example.

The problem here is that our API wrappers for each window are not consistent. If a window creates a child window, its parent windows do not know about the new window. If the parent window then requested the children of that window, it would return `[]`. (I hope that makes sense, its difficult to explain via a comment :-) )

I think your suggestion may be what we need to use in OpenFin to maintain state across apps. Either that, or we only allow getting child windows of the current window (i.e. a static method or similar). This would make windows stateless so we wouldn't need to worry about maintaining state across windows.

As for listeners not being communicated across windows, I think that the current behavior is the correct behavior. Listeners should only be relevant for the context they are currently running in. A parent shouldn't need to know about a child windows listeners. Maybe this needs to be communicated in the documentation somewhere.

**Comment by nkolba** [comment]
Sorry, just getting back to this... 

So is the issue that when using window.open, the OpenFin API (the inner window) is not aware of the creation of the child?

**Comment by BenLambertNcl** [comment]
@nkolba The issue is with our window object having conflicting states in relation to child windows, as there is no method in either Electron or OpenFin to keep track of this. This would happen if a user used `window.open` instead of the API. The initial idea was to make it easier to get all child windows, but I don't think it really provides much value. I think removing this method is the solution, and keeping the window stateless. A user of the API would usually be calling `const win = new Window(...)` and keeping the reference to the child window anyway, making this method unnecessary, as well as allowing users to use `window.open`. 

@JohnEz What do you think?

**Comment by BenLambertNcl** [comment]
After conversations offline, we are going to change the OpenFin implementation to always open `fin.desktop.Application` and monitor the state of the application ourselves, possibly needing an invisible hidden window to act as the main process like in electron. This will mean the process model for window between the 2 containers is much similar than before.

**Comment by ColinEberhardt** [comment]
I had a good play with the OpenFin & Electron window APIs, mostly for my own benefit! Anyhow, here are my notes in case they are useful:

# OpenFin

 - You can obtain the initially opened window via Application.getWindow()
 - Windows are created via `fin.desktop.Window`, with various options passed
 - You can obtain the parent via Window.getParentWindow, and access parent context, getParentWindow().getNativeWindow()
 - You can obtain all other applications windows via Application.getChildWindows()
 - OpenFin does not maintain any sort of window hierarchy, getParentWindow() always returns the window created via app.json, and all others appear in the Application.getChildWindows() array, no matter which window was the 'opener'
 - All windows are within the same process
 - doesn't have the concept of child windows, instead you use alwaysOnTop (although this doesn't minimize together with the parent)

Using window.open
 - Creates a new OpenFin window with a UUID for the name, and autoShow set to true (with new fin.desltop.Window this defaults to false)
 - window.opener returns the native parent, i.e. the same as getParentWindow().getNativeWindow()
 - window.opener behaves differently from getParentWindow() in that it always references the native window that it was opened from, rather than the window constructed via app.json


# Browser

 - New windows opened via window.open
 - Has the same behaviour as above, same process, and able to access same context

# Electron

 - Windows are created via new BrowserWindow, within the main process.
 - Windows can be created in the renderer process using the 'remote' interface, although this is just a proxy interface, with the window still being created and managed by the main process
 - Each new window is in a different process
 - You can obtain all the windows via the static BrowserWindow.getAllWindows() method
 - You can set a window as a parent on construction, in order to create a child window. You can navigate this relationship via getParentWindow / getChildWindow

 Using window.open
  - Creates a window via BrowserWindow, but returns a proxy, BrowserWindowProxy
  - window.opener returns a BrowserWindowProxy, with a restrictive API
  - The parent / child are different processes, so you can only postMessage

Using window.open with the sandbox turned on via `--enable-sandbox`
  - Works as per the Chrome browser, creating a new window in the same process.

**Comment by BenLambertNcl** [comment]
@ColinEberhardt I have added your comment to the [wiki](https://github.com/symphonyoss/ContainerJS/wiki/Window-API) so we have this information if we need it once this issue is closed.
