### ISSUE TITLE
A better release process

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#213]
For releases I'd like to see the following:

1. Git tags
2. npm releases
3. (optional) automatic major / minor / patch increments based on the commit history.

Currently we have (2), but not (1), which makes it really hard to determine which version of the codebase relates to each npm version of the code.

**Comment by BenLambertNcl** [comment]
Using lerna gives us 1). We can do:
- `lerna publish --independant` (independant bumps each version independantly, rather than bumping the whole lerna repo)
- Select version increment for each package (major, minor, patch etc.)
- Lerna then publishes to npm, bumps version numbers, creates tags for all projects and pushes to git. I'm not sure how easy this would be to automate but its much nicer than doing the version bumping manually and tagging etc.

**Comment by BenLambertNcl** [comment]
I feel like this issue can be closed (as we now have 1 and 2, with a separate issue for 3). Feel free to reopen if we need to discuss this further.

**Comment by ColinEberhardt** [comment]
I agree 👍
