### ISSUE TITLE
Explore the use of window.open

### ISSUE THREAD

**Issue by ColinEberhardt** [symphonyoss/ContainerJS#81]
In the Symphony meeting yesterday I heard from @lneir - who is writing SymphonyElectron (https://github.com/symphonyoss/SymphonyElectron/), which is going to host the Symphony Web Application - that they are using window.open within the Symphony Web codebase.

Electron provides support for window.open, creating a `BrowserWindow` and returning a proxy:

https://github.com/electron/electron/blob/master/docs/api/window-open.md

Currently we have a `ssf.Window` API - if window.open can be made to provide the same functionality, we'd be much better off using this.

I think we need to do the following:
 - understand the limitations of `window.open` within Electron. The document indicates that limitations exist, but doesn't give any detail
 - adapt OpenFin - my guess is that it doesn't support window.open, so we'd have to modify the `ssf.Window` API that already acts as the polyfill here,

**Comment by BenLambertNcl** [comment]
From my understanding:
* `window.open` could be used in electron instead of `BrowserWindow` without problems.
* OpenFin has its own `fin.desktop.Window()` constructor. Overriding `window.open` with this causes errors, as internally, the OpenFin window constructor seems to call `window.open` which in turn calls the OpenFin constructor, creating an infinite loop. We could use `window.open` over the OpenFin constructor, but this would also only allow us to create child windows (non child windows are currently created as new Applications, so they behave the same as electron).

Also, the proxy window that is returned only provides very limited capabilities (for example, the opener cannot maximize and minimize the new window, hide/show the new window etc.) in either container.

This was why we went with moving away from `window.open` (So we could keep the API's the same). However, if the only reason for sticking with this is to get the `BrowserWindow` proxy object back, there could be another solution. Currently I am looking at replacing the electron IPC calls with the `remote` module (as this has been added into sandboxed preload scripts, which didn't work when we first started). Using this, we can access the full window object (not just a proxy). However, if the goal is to use the HTML5 api, then we would have to figure out a way to make the OpenFin constructor call the unmodified `window.open` function, or use `window.open` and have less control over the new window.

**Comment by ColinEberhardt** [comment]
Thanks for the info @BenLambertNcl - really useful. It might be worth bringing someone from OpenFin in on this discussion.

@nkolba we've been discussing the use of `window.open` within the Symphony HTML5 application and whether this should become the 'standard' for containers. As you can see from the discussions above @BenLambertNcl has had problems with adapting `window.open` so that it uses the OpenFin APIs. 

As it stands, this may be an obstacle to getting the Symphony HTML5 messaging app working in an OpenFin container.

**Comment by nkolba** [comment]
@ColinEberhardt @BenLambertNcl: Our approach is to preserve and leverage as much of the existing web platform as possible, which is why we leave window.open intact without side effects and actually leverage it to open child windows.

**Comment by ColinEberhardt** [comment]
@lneir I've noticed the addition of Activity and RegisterBoundsChanged APIs on the Symphony Confluence:

https://symphonyoss.atlassian.net/wiki/display/WGDWAPI/RegisterBoundsChange+API
https://symphonyoss.atlassian.net/wiki/display/WGDWAPI/Activate+API

Both of these are 'global style' APIs that allow you to interact with Windows. I think a better option is to build up an API on the Window object. This is what we have been exploring with this project:

https://symphonyoss.github.io/containerjs/docs/window

**Comment by BenLambertNcl** [comment]
I feel like this issue can be closed. There is documentation from @ColinEberhardt about using window.open [here](https://github.com/symphonyoss/ContainerJS/wiki/Window-API#windowopen), the closed PR #195 covers some of the technical challenges and #219 covers using window.open as a possible configurable process model option. If anyone feels there is more to dicuss, please feel free to reopen :-)
